CREATE database my_autoservice;
use my_autoservice;

CREATE TABLE AUTHORISE(
ID INT NOT NULL,
LOGIN VARCHAR(500) NOT NULL,
PASS VARCHAR(500) NOT NULL,
ROLE VARCHAR(50) NOT NULL,
primary key (id)
);

CREATE TABLE VLASNIK(
ID INT auto_increment NOT NULL,
NAME VARCHAR(50) NOT NULL,
SURNAME VARCHAR(50) NOT NULL,
MIDDLENAME VARCHAR(50) NOT NULL,
MOBILE_PHONE INT NOT NULL,
DATE_BIRTHDAY DATE NOT NULL,
PRIMARY KEY(ID, SURNAME, NAME,  MIDDLENAME,  MOBILE_PHONE, DATE_BIRTHDAY),
INDEX(ID),
INDEX(SURNAME),
INDEX(NAME),
INDEX(MIDDLENAME)
);
CREATE TABLE AUTO (
ID INT auto_increment NOT NULL,
MODEL VARCHAR(100) NOT NULL,
NUMBER VARCHAR(100) NOT NULL,
DATE_OF_MADE DATE NOT NULL,
NAME_1 VARCHAR(50) NOT NULL,
SURNAME_1 VARCHAR(50) NOT NULL,
MIDDLENAME_1 VARCHAR(50) NOT NULL,
PRIMARY KEY(ID, MODEL, NUMBER),
INDEX(ID),
INDEX(MODEL),
INDEX(NUMBER),
INDEX(DATE_OF_MADE),
FOREIGN KEY (NAME_1) REFERENCES VLASNIK(NAME) ON DELETE CASCADE,
FOREIGN KEY (SURNAME_1) REFERENCES VLASNIK(SURNAME) ON DELETE CASCADE,
FOREIGN KEY (MIDDLENAME_1) REFERENCES VLASNIK(MIDDLENAME) ON DELETE CASCADE
);


CREATE TABLE MECHANIC(
ID INT AUTO_INCREMENT NOT NULL,
NAME VARCHAR(50) NOT NULL,
MIDDLENAME VARCHAR(50) NOT NULL,
SURNAME VARCHAR(50) NOT NULL,
EXPERIENCE INT NOT NULL,
TYPE_WORK VARCHAR(9000) NOT NULL,
AGE INT NOT NULL,
PRIMARY KEY (ID, NAME, SURNAME, MIDDLENAME, EXPERIENCE),
INDEX(NAME),
INDEX(SURNAME),
INDEX(MIDDLENAME),
INDEX(EXPERIENCE)
);

CREATE TABLE ORDERED (
ID INT AUTO_INCREMENT NOT NULL,
MODEL VARCHAR(100) NOT NULL,
NUMBER VARCHAR(100) NULL,
DATE_OF_MADE DATE NOT NULL,
NAME VARCHAR(50) NOT NULL,
SURNAME VARCHAR(50) NOT NULL,
MIDDLENAME VARCHAR(50) NOT NULL,
COST DOUBLE NOT NULL,
DATE_OF_ISSUE DATE,
TYPE_WORK VARCHAR(100) NOT NULL,
DATE_START DATE NOT NULL,
DATE_END DATE,
EXECUTOR VARCHAR(50) NOT NULL,
EXPERIENCE_EXECUTOR INT NOT NULL,
PRIMARY KEY(ID), 
FOREIGN KEY (MODEL) REFERENCES AUTO(MODEL) ON DELETE CASCADE,
FOREIGN KEY (NUMBER) REFERENCES AUTO(NUMBER) ON DELETE CASCADE,
FOREIGN KEY (DATE_OF_MADE) REFERENCES AUTO(DATE_OF_MADE) ON DELETE CASCADE,
FOREIGN KEY (NAME) REFERENCES VLASNIK(NAME) ON DELETE CASCADE,
FOREIGN KEY (SURNAME) REFERENCES VLASNIK(SURNAME) ON DELETE CASCADE,
FOREIGN KEY (MIDDLENAME) REFERENCES VLASNIK(MIDDLENAME) ON DELETE CASCADE,
FOREIGN KEY (EXECUTOR) REFERENCES MECHANIC(SURNAME) ON DELETE CASCADE,
FOREIGN KEY (EXPERIENCE_EXECUTOR) REFERENCES MECHANIC(EXPERIENCE) ON DELETE CASCADE
);


-- заполнение таблицы данных для авторизаци
INSERT INTO `my_autoservice`.`authorise` (`ID`, `LOGIN`, `PASS`, `ROLE`) VALUES ('1', 'admin', 'admin', 'admin');
INSERT INTO `my_autoservice`.`authorise` (`ID`, `LOGIN`, `PASS`, `ROLE`) VALUES ('2', 'and', '1234', 'mech');

